/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Gender = IDL.Variant({
  'other' : IDL.Null,
  'female' : IDL.Null,
  'male' : IDL.Null,
});
export const Location = IDL.Record({
  'destination' : IDL.Text,
  'startLocation' : IDL.Text,
});
export const Vibe = IDL.Variant({
  'music' : IDL.Null,
  'networking' : IDL.Null,
  'silent' : IDL.Null,
});
export const Role = IDL.Variant({ 'driver' : IDL.Null, 'rider' : IDL.Null });
export const Profile = IDL.Record({
  'licensePlate' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'role' : Role,
  'trustScore' : IDL.Float64,
  'email' : IDL.Text,
  'vehicleModel' : IDL.Opt(IDL.Text),
  'gender' : Gender,
  'walletBalance' : IDL.Int,
});
export const Rating = IDL.Record({
  'rideId' : IDL.Nat,
  'reviewText' : IDL.Text,
  'toUserId' : IDL.Principal,
  'stars' : IDL.Int,
  'fromUserId' : IDL.Principal,
});
export const RideStatus = IDL.Variant({
  'scheduled' : IDL.Null,
  'active' : IDL.Null,
  'cancelled' : IDL.Null,
  'completed' : IDL.Null,
});
export const Ride = IDL.Record({
  'status' : RideStatus,
  'driverId' : IDL.Principal,
  'vibe' : Vibe,
  'femaleOnly' : IDL.Bool,
  'seatsTotal' : IDL.Int,
  'seatsAvailable' : IDL.Int,
  'dateTime' : IDL.Text,
  'location' : Location,
});
export const TransactionType = IDL.Variant({
  'credit' : IDL.Null,
  'debit' : IDL.Null,
});
export const Transaction = IDL.Record({
  'transactionType' : TransactionType,
  'userId' : IDL.Principal,
  'rideId' : IDL.Opt(IDL.Nat),
  'amount' : IDL.Int,
});
export const BookingStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});

export const idlService = IDL.Service({
  'createProfile' : IDL.Func([IDL.Text, IDL.Text, Gender], [], []),
  'createRide' : IDL.Func(
      [Location, IDL.Text, IDL.Int, IDL.Bool, Vibe],
      [IDL.Nat],
      [],
    ),
  'getAllProfiles' : IDL.Func([], [IDL.Vec(Profile)], ['query']),
  'getRatingsByUserId' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Rating)],
      ['query'],
    ),
  'getRidesByDriverId' : IDL.Func([IDL.Principal], [IDL.Vec(Ride)], ['query']),
  'getRidesByStatus' : IDL.Func([RideStatus], [IDL.Vec(Ride)], ['query']),
  'getTransactionsByUserId' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'updateBookingStatus' : IDL.Func([IDL.Nat, BookingStatus], [], []),
  'updateRideStatus' : IDL.Func([IDL.Nat, RideStatus], [], []),
  'updateWalletBalance' : IDL.Func([IDL.Int], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Gender = IDL.Variant({
    'other' : IDL.Null,
    'female' : IDL.Null,
    'male' : IDL.Null,
  });
  const Location = IDL.Record({
    'destination' : IDL.Text,
    'startLocation' : IDL.Text,
  });
  const Vibe = IDL.Variant({
    'music' : IDL.Null,
    'networking' : IDL.Null,
    'silent' : IDL.Null,
  });
  const Role = IDL.Variant({ 'driver' : IDL.Null, 'rider' : IDL.Null });
  const Profile = IDL.Record({
    'licensePlate' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'role' : Role,
    'trustScore' : IDL.Float64,
    'email' : IDL.Text,
    'vehicleModel' : IDL.Opt(IDL.Text),
    'gender' : Gender,
    'walletBalance' : IDL.Int,
  });
  const Rating = IDL.Record({
    'rideId' : IDL.Nat,
    'reviewText' : IDL.Text,
    'toUserId' : IDL.Principal,
    'stars' : IDL.Int,
    'fromUserId' : IDL.Principal,
  });
  const RideStatus = IDL.Variant({
    'scheduled' : IDL.Null,
    'active' : IDL.Null,
    'cancelled' : IDL.Null,
    'completed' : IDL.Null,
  });
  const Ride = IDL.Record({
    'status' : RideStatus,
    'driverId' : IDL.Principal,
    'vibe' : Vibe,
    'femaleOnly' : IDL.Bool,
    'seatsTotal' : IDL.Int,
    'seatsAvailable' : IDL.Int,
    'dateTime' : IDL.Text,
    'location' : Location,
  });
  const TransactionType = IDL.Variant({
    'credit' : IDL.Null,
    'debit' : IDL.Null,
  });
  const Transaction = IDL.Record({
    'transactionType' : TransactionType,
    'userId' : IDL.Principal,
    'rideId' : IDL.Opt(IDL.Nat),
    'amount' : IDL.Int,
  });
  const BookingStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  
  return IDL.Service({
    'createProfile' : IDL.Func([IDL.Text, IDL.Text, Gender], [], []),
    'createRide' : IDL.Func(
        [Location, IDL.Text, IDL.Int, IDL.Bool, Vibe],
        [IDL.Nat],
        [],
      ),
    'getAllProfiles' : IDL.Func([], [IDL.Vec(Profile)], ['query']),
    'getRatingsByUserId' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Rating)],
        ['query'],
      ),
    'getRidesByDriverId' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Ride)],
        ['query'],
      ),
    'getRidesByStatus' : IDL.Func([RideStatus], [IDL.Vec(Ride)], ['query']),
    'getTransactionsByUserId' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'updateBookingStatus' : IDL.Func([IDL.Nat, BookingStatus], [], []),
    'updateRideStatus' : IDL.Func([IDL.Nat, RideStatus], [], []),
    'updateWalletBalance' : IDL.Func([IDL.Int], [], []),
  });
};

export const init = ({ IDL }) => { return []; };