/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type BookingStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export type Gender = { 'other' : null } |
  { 'female' : null } |
  { 'male' : null };
export interface Location { 'destination' : string, 'startLocation' : string }
export interface Profile {
  'licensePlate' : [] | [string],
  'name' : string,
  'role' : Role,
  'trustScore' : number,
  'email' : string,
  'vehicleModel' : [] | [string],
  'gender' : Gender,
  'walletBalance' : bigint,
}
export interface Rating {
  'rideId' : bigint,
  'reviewText' : string,
  'toUserId' : Principal,
  'stars' : bigint,
  'fromUserId' : Principal,
}
export interface Ride {
  'status' : RideStatus,
  'driverId' : Principal,
  'vibe' : Vibe,
  'femaleOnly' : boolean,
  'seatsTotal' : bigint,
  'seatsAvailable' : bigint,
  'dateTime' : string,
  'location' : Location,
}
export type RideStatus = { 'scheduled' : null } |
  { 'active' : null } |
  { 'cancelled' : null } |
  { 'completed' : null };
export type Role = { 'driver' : null } |
  { 'rider' : null };
export interface Transaction {
  'transactionType' : TransactionType,
  'userId' : Principal,
  'rideId' : [] | [bigint],
  'amount' : bigint,
}
export type TransactionType = { 'credit' : null } |
  { 'debit' : null };
export type Vibe = { 'music' : null } |
  { 'networking' : null } |
  { 'silent' : null };
export interface _SERVICE {
  'createProfile' : ActorMethod<[string, string, Gender], undefined>,
  'createRide' : ActorMethod<[Location, string, bigint, boolean, Vibe], bigint>,
  'getAllProfiles' : ActorMethod<[], Array<Profile>>,
  'getRatingsByUserId' : ActorMethod<[Principal], Array<Rating>>,
  'getRidesByDriverId' : ActorMethod<[Principal], Array<Ride>>,
  'getRidesByStatus' : ActorMethod<[RideStatus], Array<Ride>>,
  'getTransactionsByUserId' : ActorMethod<[Principal], Array<Transaction>>,
  'updateBookingStatus' : ActorMethod<[bigint, BookingStatus], undefined>,
  'updateRideStatus' : ActorMethod<[bigint, RideStatus], undefined>,
  'updateWalletBalance' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];