/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Transaction {
    transactionType: TransactionType;
    userId: Principal;
    rideId?: bigint;
    amount: bigint;
}
export interface Location {
    destination: string;
    startLocation: string;
}
export interface Ride {
    status: RideStatus;
    driverId: Principal;
    vibe: Vibe;
    femaleOnly: boolean;
    seatsTotal: bigint;
    seatsAvailable: bigint;
    dateTime: string;
    location: Location;
}
export interface Rating {
    rideId: bigint;
    reviewText: string;
    toUserId: Principal;
    stars: bigint;
    fromUserId: Principal;
}
export interface Profile {
    licensePlate?: string;
    name: string;
    role: Role;
    trustScore: number;
    email: string;
    vehicleModel?: string;
    gender: Gender;
    walletBalance: bigint;
}
export enum BookingStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum Gender {
    other = "other",
    female = "female",
    male = "male"
}
export enum RideStatus {
    scheduled = "scheduled",
    active = "active",
    cancelled = "cancelled",
    completed = "completed"
}
export enum Role {
    driver = "driver",
    rider = "rider"
}
export enum TransactionType {
    credit = "credit",
    debit = "debit"
}
export enum Vibe {
    music = "music",
    networking = "networking",
    silent = "silent"
}
export interface backendInterface {
    createProfile(name: string, email: string, gender: Gender): Promise<void>;
    createRide(location: Location, dateTime: string, seatsTotal: bigint, femaleOnly: boolean, vibe: Vibe): Promise<bigint>;
    getAllProfiles(): Promise<Array<Profile>>;
    getRatingsByUserId(userId: Principal): Promise<Array<Rating>>;
    getRidesByDriverId(driverId: Principal): Promise<Array<Ride>>;
    getRidesByStatus(status: RideStatus): Promise<Array<Ride>>;
    getTransactionsByUserId(userId: Principal): Promise<Array<Transaction>>;
    updateBookingStatus(bookingId: bigint, newStatus: BookingStatus): Promise<void>;
    updateRideStatus(rideId: bigint, newStatus: RideStatus): Promise<void>;
    updateWalletBalance(newBalance: bigint): Promise<void>;
}
import type { BookingStatus as _BookingStatus, Gender as _Gender, Location as _Location, Profile as _Profile, Ride as _Ride, RideStatus as _RideStatus, Role as _Role, Transaction as _Transaction, TransactionType as _TransactionType, Vibe as _Vibe } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createProfile(arg0: string, arg1: string, arg2: Gender): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createProfile(arg0, arg1, to_candid_Gender_n1(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProfile(arg0, arg1, to_candid_Gender_n1(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async createRide(arg0: Location, arg1: string, arg2: bigint, arg3: boolean, arg4: Vibe): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createRide(arg0, arg1, arg2, arg3, to_candid_Vibe_n3(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRide(arg0, arg1, arg2, arg3, to_candid_Vibe_n3(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async getAllProfiles(): Promise<Array<Profile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProfiles();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProfiles();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRatingsByUserId(arg0: Principal): Promise<Array<Rating>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRatingsByUserId(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRatingsByUserId(arg0);
            return result;
        }
    }
    async getRidesByDriverId(arg0: Principal): Promise<Array<Ride>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRidesByDriverId(arg0);
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRidesByDriverId(arg0);
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRidesByStatus(arg0: RideStatus): Promise<Array<Ride>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRidesByStatus(to_candid_RideStatus_n20(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRidesByStatus(to_candid_RideStatus_n20(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTransactionsByUserId(arg0: Principal): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactionsByUserId(arg0);
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactionsByUserId(arg0);
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateBookingStatus(arg0: bigint, arg1: BookingStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBookingStatus(arg0, to_candid_BookingStatus_n28(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBookingStatus(arg0, to_candid_BookingStatus_n28(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateRideStatus(arg0: bigint, arg1: RideStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRideStatus(arg0, to_candid_RideStatus_n20(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRideStatus(arg0, to_candid_RideStatus_n20(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateWalletBalance(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateWalletBalance(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateWalletBalance(arg0);
            return result;
        }
    }
}
function from_candid_Gender_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Gender): Gender {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Profile_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Profile): Profile {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_RideStatus_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RideStatus): RideStatus {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_Ride_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Ride): Ride {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_Role_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_TransactionType_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionType): TransactionType {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_Transaction_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Transaction): Transaction {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_Vibe_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Vibe): Vibe {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _RideStatus;
    driverId: Principal;
    vibe: _Vibe;
    femaleOnly: boolean;
    seatsTotal: bigint;
    seatsAvailable: bigint;
    dateTime: string;
    location: _Location;
}): {
    status: RideStatus;
    driverId: Principal;
    vibe: Vibe;
    femaleOnly: boolean;
    seatsTotal: bigint;
    seatsAvailable: bigint;
    dateTime: string;
    location: Location;
} {
    return {
        status: from_candid_RideStatus_n16(_uploadFile, _downloadFile, value.status),
        driverId: value.driverId,
        vibe: from_candid_Vibe_n18(_uploadFile, _downloadFile, value.vibe),
        femaleOnly: value.femaleOnly,
        seatsTotal: value.seatsTotal,
        seatsAvailable: value.seatsAvailable,
        dateTime: value.dateTime,
        location: value.location
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    transactionType: _TransactionType;
    userId: Principal;
    rideId: [] | [bigint];
    amount: bigint;
}): {
    transactionType: TransactionType;
    userId: Principal;
    rideId?: bigint;
    amount: bigint;
} {
    return {
        transactionType: from_candid_TransactionType_n25(_uploadFile, _downloadFile, value.transactionType),
        userId: value.userId,
        rideId: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.rideId)),
        amount: value.amount
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    licensePlate: [] | [string];
    name: string;
    role: _Role;
    trustScore: number;
    email: string;
    vehicleModel: [] | [string];
    gender: _Gender;
    walletBalance: bigint;
}): {
    licensePlate?: string;
    name: string;
    role: Role;
    trustScore: number;
    email: string;
    vehicleModel?: string;
    gender: Gender;
    walletBalance: bigint;
} {
    return {
        licensePlate: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.licensePlate)),
        name: value.name,
        role: from_candid_Role_n9(_uploadFile, _downloadFile, value.role),
        trustScore: value.trustScore,
        email: value.email,
        vehicleModel: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.vehicleModel)),
        gender: from_candid_Gender_n11(_uploadFile, _downloadFile, value.gender),
        walletBalance: value.walletBalance
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    driver: null;
} | {
    rider: null;
}): Role {
    return "driver" in value ? Role.driver : "rider" in value ? Role.rider : value;
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    female: null;
} | {
    male: null;
}): Gender {
    return "other" in value ? Gender.other : "female" in value ? Gender.female : "male" in value ? Gender.male : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    scheduled: null;
} | {
    active: null;
} | {
    cancelled: null;
} | {
    completed: null;
}): RideStatus {
    return "scheduled" in value ? RideStatus.scheduled : "active" in value ? RideStatus.active : "cancelled" in value ? RideStatus.cancelled : "completed" in value ? RideStatus.completed : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    music: null;
} | {
    networking: null;
} | {
    silent: null;
}): Vibe {
    return "music" in value ? Vibe.music : "networking" in value ? Vibe.networking : "silent" in value ? Vibe.silent : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    credit: null;
} | {
    debit: null;
}): TransactionType {
    return "credit" in value ? TransactionType.credit : "debit" in value ? TransactionType.debit : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Ride>): Array<Ride> {
    return value.map((x)=>from_candid_Ride_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Transaction>): Array<Transaction> {
    return value.map((x)=>from_candid_Transaction_n23(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Profile>): Array<Profile> {
    return value.map((x)=>from_candid_Profile_n6(_uploadFile, _downloadFile, x));
}
function to_candid_BookingStatus_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus): _BookingStatus {
    return to_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function to_candid_Gender_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): _Gender {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_RideStatus_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RideStatus): _RideStatus {
    return to_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function to_candid_Vibe_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Vibe): _Vibe {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): {
    other: null;
} | {
    female: null;
} | {
    male: null;
} {
    return value == Gender.other ? {
        other: null
    } : value == Gender.female ? {
        female: null
    } : value == Gender.male ? {
        male: null
    } : value;
}
function to_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RideStatus): {
    scheduled: null;
} | {
    active: null;
} | {
    cancelled: null;
} | {
    completed: null;
} {
    return value == RideStatus.scheduled ? {
        scheduled: null
    } : value == RideStatus.active ? {
        active: null
    } : value == RideStatus.cancelled ? {
        cancelled: null
    } : value == RideStatus.completed ? {
        completed: null
    } : value;
}
function to_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == BookingStatus.pending ? {
        pending: null
    } : value == BookingStatus.approved ? {
        approved: null
    } : value == BookingStatus.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Vibe): {
    music: null;
} | {
    networking: null;
} | {
    silent: null;
} {
    return value == Vibe.music ? {
        music: null
    } : value == Vibe.networking ? {
        networking: null
    } : value == Vibe.silent ? {
        silent: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
